"""
REST API for the SQL Agent (the "API Endpoint" module).

Exposes `sql_agent.ask(question)` over HTTP so other modules (Chat UI, etc.)
or external clients can call it without importing the Python package
directly.

Run with:
    uvicorn api:app --reload

Interactive docs (auto-generated by FastAPI) are then at:
    http://localhost:8000/docs

Example call:
    curl -X POST http://localhost:8000/ask \\
        -H "Content-Type: application/json" \\
        -d '{"question": "What sections of GEARTAP are on Mondays?"}'
"""
from typing import Any, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from sql_agent import ask

app = FastAPI(
    title="STAI100 Course Suggestion Agent API",
    description=(
        "Translates a natural-language question about DLSU GE/elective "
        "course offerings into SQL and returns the matching sections."
    ),
    version="0.1.0",
)

# Wide-open CORS so a Chat UI module (e.g. Streamlit/Gradio, likely running
# on a different port) can call this without extra config. Tighten
# allow_origins before any real deployment.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class Message(BaseModel):
    role: str
    content: str

class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="Natural-language question about course offerings.",
        examples=["What GE subjects can I take between 12:30pm and 16:00?"],
    )
    history: Optional[list[Message]] = []


class AskResponse(BaseModel):
    question: str
    reasoning: str
    sql: str
    rows: Optional[list[dict[str, Any]]] = None
    error: Optional[str] = None
    updated_history: list[Message]


@app.get("/health")
def health() -> dict:
    """Liveness check - used by Docker/uptime checks, not the agent itself."""
    return {"status": "ok"}


@app.post("/ask", response_model=AskResponse)
def ask_endpoint(payload: AskRequest) -> dict:
    """
    Ask the SQL Agent a natural-language question and get matching course
    sections back.

    Guardrail rejections and SQL execution failures are NOT HTTP errors -
    they come back as a normal 200 response with `error` populated and
    `rows: null`, same contract as `sql_agent.ask()` itself, so a Chat UI
    can render them inline. Only genuine upstream failures (e.g. the
    DeepSeek call itself erroring out or timing out) raise a 502.
    """
    history_dicts = [{"role": msg.role, "content": msg.content} for msg in payload.history]

    try:
        result = ask(payload.question, history=history_dicts)
    except Exception as exc:  # e.g. DeepSeek timeout/auth/network failure
        raise HTTPException(
            status_code=502, detail=f"SQL Agent upstream call failed: {exc}"
        ) from exc

    # Append current exchange to send back to frontend
    new_history = history_dicts + [
        {"role": "user", "content": payload.question},
        {"role": "assistant", "content": result["raw_response"]}
    ]

    return {
        "question": result["question"],
        "reasoning": result["reasoning"],
        "sql": result["sql"],
        "rows": result["rows"],
        "error": result["error"],
        "updated_history": new_history
    }
