"""
REST API for the SQL Agent (the "API Endpoint" module).

Exposes `sql_agent.ask(question)` over HTTP so other modules (Chat UI, etc.)
or external clients can call it without importing the Python package
directly.

Run with (from the repo root):
    uvicorn apps.api:app --reload

Interactive docs (auto-generated by FastAPI) are then at:
    http://localhost:8000/docs

Example call:
    curl -X POST http://localhost:8000/ask \\
        -H "Content-Type: application/json" \\
        -d '{"question": "What sections of GEARTAP are on Mondays?"}'
"""
from typing import Any, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from sql_agent import respond

app = FastAPI(
    title="STAI100 Course Suggestion Agent API",
    description=(
        "Answers natural-language questions about DLSU GE/elective course "
        "offerings. Plain lookups are translated to SQL; requests to build a "
        "timetable are routed to a deterministic ILP scheduler that returns a "
        "verified, conflict-free schedule (and negotiates when over-constrained)."
    ),
    version="0.2.0",
)

# Wide-open CORS so a Chat UI module (e.g. Streamlit/Gradio, likely running
# on a different port) can call this without extra config. Tighten
# allow_origins before any real deployment.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class Message(BaseModel):
    role: str
    content: str

class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="Natural-language question about course offerings.",
        examples=["What GE subjects can I take between 12:30pm and 16:00?"],
    )
    history: Optional[list[Message]] = []


class AskResponse(BaseModel):
    question: str
    reasoning: str
    sql: Optional[str] = None
    rows: Optional[list[dict[str, Any]]] = None
    error: Optional[str] = None
    updated_history: list[Message]
    # Scheduling path extras (null/empty for plain lookups):
    mode: str = "lookup"                         # "lookup" | "schedule"
    relaxations: list[str] = []                  # constraints the agent loosened
    dropped_courses: list[str] = []              # courses it couldn't fit
    criteria: Optional[dict[str, Any]] = None    # C1-C7 grade from grade_schedule()


@app.get("/health")
def health() -> dict:
    """Liveness check - used by Docker/uptime checks, not the agent itself."""
    return {"status": "ok"}


@app.post("/ask", response_model=AskResponse)
def ask_endpoint(payload: AskRequest) -> dict:
    """
    Ask the agent a natural-language question.

    The agent routes the message: a request to BUILD A TIMETABLE goes to the
    deterministic ILP scheduler (returns a verified, conflict-free schedule in
    `rows`, with any `relaxations`/`dropped_courses` it negotiated and the
    `criteria` correctness check); anything else is a plain lookup translated
    to `sql`.

    Guardrail rejections and SQL execution failures are NOT HTTP errors - they
    come back as a normal 200 response with `error` populated. Only genuine
    upstream failures (e.g. the DeepSeek call erroring out or timing out) raise
    a 502.

    Args:
        payload: The validated request body (`AskRequest`) with:
            - ``question``: the natural-language question (required, non-empty);
            - ``history``: optional prior turns as ``{role, content}`` messages
              for follow-up context.

    Returns:
        A dict matching `AskResponse`: the ``question``/``reasoning``/``sql``/
        ``rows``/``error`` result, the ``updated_history`` (input history plus
        this exchange, to feed back on the next call), and the scheduling
        extras ``mode``/``relaxations``/``dropped_courses``/``criteria``.

    Raises:
        HTTPException: 502 if the upstream LLM call fails (network/auth/timeout).
    """
    history_dicts = [{"role": msg.role, "content": msg.content} for msg in payload.history]

    try:
        result = respond(payload.question, history=history_dicts)
    except Exception as exc:  # e.g. DeepSeek timeout/auth/network failure
        raise HTTPException(
            status_code=502, detail=f"Agent upstream call failed: {exc}"
        ) from exc

    # Append current exchange to send back to frontend
    new_history = history_dicts + [
        {"role": "user", "content": payload.question},
        {"role": "assistant", "content": result["raw_response"]}
    ]

    return {
        "question": result["question"],
        "reasoning": result["reasoning"],
        "sql": result.get("sql"),
        "rows": result["rows"],
        "error": result["error"],
        "updated_history": new_history,
        "mode": result.get("mode", "lookup"),
        "relaxations": result.get("relaxations", []),
        "dropped_courses": result.get("dropped_courses", []),
        "criteria": result.get("criteria"),
    }
